### ISSUE TITLE
Real time updating of time until the train leaves

### ISSUE THREAD

**Issue by Gear61** [jchio001/Will-I-Miss-Bart#14]
Unsure about this one; feel free to close this if you don't believe in it.

Pros:
- Looks neat
- More concrete representation of when the trailer is going to leave

Cons:
- Considerable strain on the UI (every cell has to refresh every second)
- Could annoy the user's eyes
- Code will be kind of messy. I'm imagining a lot of Handlers that need to be maintained or a bunch of calls to notifyDataSetChanged()

**Comment by Gear61** [comment]
Now that I've listed out the cons, I actually am siding against this feature.

**Comment by jchio001** [comment]
I already do kind of that when the user presses the "Leaving in ..." blurb.

**Comment by Gear61** [comment]
@jchio001 That's not really real-time; that's a reactive event.
