### ISSUE TITLE
Polish timer logic

### ISSUE THREAD

**Issue by Gear61** [jchio001/Will-I-Miss-Bart#36]
- Put 2 numbers further apart
- Make up/down carets bigger to increase the hitboxes
- Don't center_horizontal the "train is leaving in around..." text for consistency
- Change title copy to "How many minutes before this train do you want to be reminded about it?"
- Make the preset time not 0. This isn't a realistic time that anybody wants. Maybe start it at 10?
- Give the notification some sort of icon in the action bar. For me right now, it's just a white square

**Comment by jchio001** [comment]
Done.
