### ISSUE TITLE
Timer text is cut off

### ISSUE THREAD

**Issue by Gear61** [jchio001/Will-I-Miss-Bart#8]
Device: Google Nexus 5X
OS: Android 6.0

<img width="386" alt="screen shot 2017-09-16 at 1 29 14 pm" src="https://user-images.githubusercontent.com/1650117/30515786-2f3d28b8-9ae3-11e7-8051-f474119d805d.png">

**Comment by jchio001** [comment]
Fixed by shrinking the text size.
